package org.example.persistence.ormanager;

import java.io.Serializable;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.Optional;

public interface ORManager {

    // generate the schema in the DB
    // for given list of entity classes (and all related by OneToMany/ManyToOne) create a schema in DB
    void register(Class... entityClasses);

    // save a new object to DB, set id if autogenerated or merge into DB if id is present
    <T> T save(T o);

    <T> Optional<T> findById(Serializable id, Class<T> cls);

    <T> List<T> findAll(Class<T> cls);

    // send o -> DB row (to table)
    <T> T update(T o);

    // send o <- DB row (from table)
    <T> T refresh(T o);

    // set autogenerated id to null
    // return true if successfully deleted
    boolean delete(Object o);

}
